CREATE TABLE IF NOT EXISTS t_execution_time
(
    execution_time_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    class_name        VARCHAR(255),
    method_name       VARCHAR(255),
    execution_time    BIGINT,
    execution_date    TIMESTAMP
);
