CREATE TABLE IF NOT EXISTS t_execution_times
(
    execution_time_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    execution_time    BIGINT,
    execution_date    TIMESTAMP,
    method_id BIGINT REFERENCES t_methods (method_id)
);
